[package]
name = "dnsoverhttps"
version = "0.1.0"
authors = ["Jan-Erik Rediger <janerik@fnordig.de>"]

[dependencies]
base64 = "0.9.0"
reqwest = "0.8.4"
trust-dns = "0.13.0"
trust-dns-proto = "0.2.0"
failure = "0.1.1"
